// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_voip_carrier

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func VoipCarrierDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_sid": schema.StringAttribute{
				Computed: true,
			},
			"application_sid": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"diversion": schema.StringAttribute{
				Computed: true,
			},
			"e164_leading_plus": schema.BoolAttribute{
				Computed: true,
			},
			"inbound_auth_password": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
			},
			"inbound_auth_username": schema.StringAttribute{
				Computed: true,
			},
			"is_active": schema.BoolAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"register_from_domain": schema.StringAttribute{
				Computed:            true,
				Description:         "optional domain to apply in the From header",
				MarkdownDescription: "optional domain to apply in the From header",
			},
			"register_from_user": schema.StringAttribute{
				Computed:            true,
				Description:         "optional username to apply in the From header",
				MarkdownDescription: "optional username to apply in the From header",
			},
			"register_password": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
			},
			"register_public_ip_in_contact": schema.BoolAttribute{
				Computed:            true,
				Description:         "if true, use our public ip in the Contact header; otherwise the sip realm",
				MarkdownDescription: "if true, use our public ip in the Contact header; otherwise the sip realm",
			},
			"register_sip_realm": schema.StringAttribute{
				Computed: true,
			},
			"register_use_tls": schema.BoolAttribute{
				Computed:            true,
				Description:         "whether to REGISTER over TLS",
				MarkdownDescription: "whether to REGISTER over TLS",
			},
			"register_username": schema.StringAttribute{
				Computed: true,
			},
			"requires_register": schema.BoolAttribute{
				Computed: true,
			},
			"smpp_enquire_link_interval": schema.NumberAttribute{
				Computed: true,
			},
			"smpp_inbound_password": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
			},
			"smpp_inbound_system_id": schema.StringAttribute{
				Computed: true,
			},
			"smpp_password": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
			},
			"smpp_system_id": schema.StringAttribute{
				Computed: true,
			},
			"tech_prefix": schema.StringAttribute{
				Computed: true,
			},
			"voip_carrier_sid": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type VoipCarrierModel struct {
	AccountSid                types.String `tfsdk:"account_sid"`
	ApplicationSid            types.String `tfsdk:"application_sid"`
	Description               types.String `tfsdk:"description"`
	Diversion                 types.String `tfsdk:"diversion"`
	E164LeadingPlus           types.Bool   `tfsdk:"e164_leading_plus"`
	InboundAuthPassword       types.String `tfsdk:"inbound_auth_password"`
	InboundAuthUsername       types.String `tfsdk:"inbound_auth_username"`
	IsActive                  types.Bool   `tfsdk:"is_active"`
	Name                      types.String `tfsdk:"name"`
	RegisterFromDomain        types.String `tfsdk:"register_from_domain"`
	RegisterFromUser          types.String `tfsdk:"register_from_user"`
	RegisterPassword          types.String `tfsdk:"register_password"`
	RegisterPublicIpInContact types.Bool   `tfsdk:"register_public_ip_in_contact"`
	RegisterSipRealm          types.String `tfsdk:"register_sip_realm"`
	RegisterUseTls            types.Bool   `tfsdk:"register_use_tls"`
	RegisterUsername          types.String `tfsdk:"register_username"`
	RequiresRegister          types.Bool   `tfsdk:"requires_register"`
	SmppEnquireLinkInterval   types.Number `tfsdk:"smpp_enquire_link_interval"`
	SmppInboundPassword       types.String `tfsdk:"smpp_inbound_password"`
	SmppInboundSystemId       types.String `tfsdk:"smpp_inbound_system_id"`
	SmppPassword              types.String `tfsdk:"smpp_password"`
	SmppSystemId              types.String `tfsdk:"smpp_system_id"`
	TechPrefix                types.String `tfsdk:"tech_prefix"`
	VoipCarrierSid            types.String `tfsdk:"voip_carrier_sid"`
}
