// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_jambonz

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func JambonzProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type JambonzModel struct {
}
