// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_sip_gateway

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SipGatewayDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"inbound": schema.Int64Attribute{
				Computed: true,
			},
			"ipv4": schema.StringAttribute{
				Computed: true,
			},
			"is_active": schema.Int64Attribute{
				Computed:            true,
				Description:         "whether the gateway is active",
				MarkdownDescription: "whether the gateway is active",
			},
			"netmask": schema.NumberAttribute{
				Computed: true,
			},
			"outbound": schema.Int64Attribute{
				Computed: true,
			},
			"port": schema.NumberAttribute{
				Computed: true,
			},
			"sip_gateway_sid": schema.StringAttribute{
				Required: true,
			},
			"voip_carrier_sid": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type SipGatewayModel struct {
	Inbound        types.Int64  `tfsdk:"inbound"`
	Ipv4           types.String `tfsdk:"ipv4"`
	IsActive       types.Int64  `tfsdk:"is_active"`
	Netmask        types.Number `tfsdk:"netmask"`
	Outbound       types.Int64  `tfsdk:"outbound"`
	Port           types.Number `tfsdk:"port"`
	SipGatewaySid  types.String `tfsdk:"sip_gateway_sid"`
	VoipCarrierSid types.String `tfsdk:"voip_carrier_sid"`
}
