// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_phone_number

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func PhoneNumberDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_sid": schema.StringAttribute{
				Computed: true,
			},
			"application_sid": schema.StringAttribute{
				Computed: true,
			},
			"number": schema.StringAttribute{
				Computed: true,
			},
			"phone_number_sid": schema.StringAttribute{
				Required: true,
			},
			"voip_carrier_sid": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type PhoneNumberModel struct {
	AccountSid     types.String `tfsdk:"account_sid"`
	ApplicationSid types.String `tfsdk:"application_sid"`
	Number         types.String `tfsdk:"number"`
	PhoneNumberSid types.String `tfsdk:"phone_number_sid"`
	VoipCarrierSid types.String `tfsdk:"voip_carrier_sid"`
}
