// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_account

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_sid": schema.StringAttribute{
				Computed: true,
			},
			"device_calling_application_sid": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "account name",
				MarkdownDescription: "account name",
			},
			"registration_hook": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"method": schema.StringAttribute{
						Optional: true,
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"GET",
								"POST",
							),
						},
						Default: stringdefault.StaticString("POST"),
					},
					"password": schema.StringAttribute{
						Required:  true,
						Sensitive: true,
					},
					"url": schema.StringAttribute{
						Required: true,
					},
					"username": schema.StringAttribute{
						Required: true,
					},
					"webhook_sid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: RegistrationHookType{
					ObjectType: types.ObjectType{
						AttrTypes: RegistrationHookValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"service_provider_sid": schema.StringAttribute{
				Required: true,
			},
			"sip_realm": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "sip realm for registration",
				MarkdownDescription: "sip realm for registration",
			},
		},
	}
}

type AccountModel struct {
	AccountSid                  types.String          `tfsdk:"account_sid"`
	DeviceCallingApplicationSid types.String          `tfsdk:"device_calling_application_sid"`
	Name                        types.String          `tfsdk:"name"`
	RegistrationHook            RegistrationHookValue `tfsdk:"registration_hook"`
	ServiceProviderSid          types.String          `tfsdk:"service_provider_sid"`
	SipRealm                    types.String          `tfsdk:"sip_realm"`
}

var _ basetypes.ObjectTypable = RegistrationHookType{}

type RegistrationHookType struct {
	basetypes.ObjectType
}

func (t RegistrationHookType) Equal(o attr.Type) bool {
	other, ok := o.(RegistrationHookType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RegistrationHookType) String() string {
	return "RegistrationHookType"
}

func (t RegistrationHookType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return nil, diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return nil, diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return nil, diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RegistrationHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewRegistrationHookValueNull() RegistrationHookValue {
	return RegistrationHookValue{
		state: attr.ValueStateNull,
	}
}

func NewRegistrationHookValueUnknown() RegistrationHookValue {
	return RegistrationHookValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRegistrationHookValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RegistrationHookValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RegistrationHookValue Attribute Value",
				"While creating a RegistrationHookValue value, a missing attribute value was detected. "+
					"A RegistrationHookValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RegistrationHookValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RegistrationHookValue Attribute Type",
				"While creating a RegistrationHookValue value, an invalid attribute value was detected. "+
					"A RegistrationHookValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RegistrationHookValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RegistrationHookValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RegistrationHookValue Attribute Value",
				"While creating a RegistrationHookValue value, an extra attribute value was detected. "+
					"A RegistrationHookValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RegistrationHookValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRegistrationHookValueUnknown(), diags
	}

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return NewRegistrationHookValueUnknown(), diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return NewRegistrationHookValueUnknown(), diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return NewRegistrationHookValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewRegistrationHookValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return NewRegistrationHookValueUnknown(), diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return NewRegistrationHookValueUnknown(), diags
	}

	return RegistrationHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewRegistrationHookValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RegistrationHookValue {
	object, diags := NewRegistrationHookValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRegistrationHookValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RegistrationHookType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRegistrationHookValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRegistrationHookValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRegistrationHookValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRegistrationHookValueMust(RegistrationHookValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RegistrationHookType) ValueType(ctx context.Context) attr.Value {
	return RegistrationHookValue{}
}

var _ basetypes.ObjectValuable = RegistrationHookValue{}

type RegistrationHookValue struct {
	Method     basetypes.StringValue `tfsdk:"method"`
	Password   basetypes.StringValue `tfsdk:"password"`
	Url        basetypes.StringValue `tfsdk:"url"`
	Username   basetypes.StringValue `tfsdk:"username"`
	WebhookSid basetypes.StringValue `tfsdk:"webhook_sid"`
	state      attr.ValueState
}

func (v RegistrationHookValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["method"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["webhook_sid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Method.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["method"] = val

		val, err = v.Password.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		val, err = v.WebhookSid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["webhook_sid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RegistrationHookValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RegistrationHookValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RegistrationHookValue) String() string {
	return "RegistrationHookValue"
}

func (v RegistrationHookValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"method":      v.Method,
			"password":    v.Password,
			"url":         v.Url,
			"username":    v.Username,
			"webhook_sid": v.WebhookSid,
		})

	return objVal, diags
}

func (v RegistrationHookValue) Equal(o attr.Value) bool {
	other, ok := o.(RegistrationHookValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Method.Equal(other.Method) {
		return false
	}

	if !v.Password.Equal(other.Password) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	if !v.WebhookSid.Equal(other.WebhookSid) {
		return false
	}

	return true
}

func (v RegistrationHookValue) Type(ctx context.Context) attr.Type {
	return RegistrationHookType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RegistrationHookValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}
}
