// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_sip_gateway

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SipGatewayResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"inbound": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"ipv4": schema.StringAttribute{
				Required: true,
			},
			"is_active": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"netmask": schema.NumberAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "CIDR prefix length for the gateway network",
				MarkdownDescription: "CIDR prefix length for the gateway network",
			},
			"outbound": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"port": schema.NumberAttribute{
				Optional: true,
				Computed: true,
			},
			"sip_gateway_sid": schema.StringAttribute{
				Computed: true,
			},
			"voip_carrier_sid": schema.StringAttribute{
				Required:            true,
				Description:         "voip carrier that provides this gateway",
				MarkdownDescription: "voip carrier that provides this gateway",
			},
		},
	}
}

type SipGatewayModel struct {
	Inbound        types.Bool   `tfsdk:"inbound"`
	Ipv4           types.String `tfsdk:"ipv4"`
	IsActive       types.Bool   `tfsdk:"is_active"`
	Netmask        types.Number `tfsdk:"netmask"`
	Outbound       types.Bool   `tfsdk:"outbound"`
	Port           types.Number `tfsdk:"port"`
	SipGatewaySid  types.String `tfsdk:"sip_gateway_sid"`
	VoipCarrierSid types.String `tfsdk:"voip_carrier_sid"`
}
