// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// A data source is one read operation. It shares the resource's binding and the
// resource's conversion fragments, so a lookup and a managed record cannot
// disagree about how a field is decoded.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/datasource_account"
)

var (
	_ datasource.DataSource              = (*accountDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*accountDataSource)(nil)
)

func NewAccountDataSource() datasource.DataSource { return &accountDataSource{} }

type accountDataSource struct {
	client *jambonzapi.ClientWithResponses
}

func (d *accountDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_account"
}

func (d *accountDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_account.AccountDataSourceSchema(ctx)
}

func (d *accountDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*jambonzapi.ClientWithResponses)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *jambonzapi.ClientWithResponses")
		return
	}
	d.client = client
}

func (d *accountDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data datasource_account.AccountModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.AccountSid.ValueString()
	api, err := d.client.GetAccountWithResponse(ctx, pathUUID(id))
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	// Unlike a resource's read, a 404 here is an error. A data source names a
	// record the configuration depends on; silently yielding nothing would push the
	// failure into whatever referenced it.
	if api.StatusCode() == http.StatusNotFound {
		resp.Diagnostics.AddError("Not found", "no account with account_sid "+id)
		return
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	d.apply(ctx, &data, api.JSON200, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// apply copies the API representation onto the Terraform model.
func (d *accountDataSource) apply(ctx context.Context, data *datasource_account.AccountModel, p *jambonzapi.Account, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.AccountSid = uuidPointerValue(p.AccountSid)
	data.DeviceCallingApplicationSid = uuidPointerValue(p.DeviceCallingApplicationSid)
	data.Name = types.StringValue(string(p.Name))

	if p.RegistrationHook == nil {
		data.RegistrationHook = datasource_account.NewRegistrationHookValueNull()
	} else {
		registrationHook, d := datasource_account.NewRegistrationHookValue(
			data.RegistrationHook.AttributeTypes(ctx),
			map[string]attr.Value{
				"method":      types.StringValue(string(p.RegistrationHook.Method)),
				"password":    types.StringValue(string(p.RegistrationHook.Password)),
				"url":         types.StringValue(string(p.RegistrationHook.Url)),
				"username":    types.StringValue(string(p.RegistrationHook.Username)),
				"webhook_sid": uuidPointerValue(p.RegistrationHook.WebhookSid),
			},
		)
		diags.Append(d...)
		data.RegistrationHook = registrationHook
	}
	data.ServiceProviderSid = uuidValue(p.ServiceProviderSid)
	data.SipRealm = types.StringPointerValue((*string)(p.SipRealm))
}
