// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// Sources: provider_code_spec.json for the schema, build/openapi.tf.json for the
// wire contract, and codegen/tooling/schemas/acceptance.json for the values —
// see that file for why the values cannot come from the other two.
//
// These are acceptance tests: they need TF_ACC=1 and a live api-server, which
// test/docker-compose.yml provides and `make testacc` starts. Without TF_ACC
// they skip.
//
// What the four steps are for, in the order they run:
//
//  1. apply the MINIMUM configuration. Every optional attribute is left out,
//     so every one of them is planned as unknown, and an attribute still
//     unknown when apply returns ends the run with "provider returned invalid
//     result object after apply". This step is the whole reason the file
//     exists.
//  2. plan again and require the plan to be empty. terraform-plugin-testing
//     does this after every apply. It catches the opposite failure: an
//     attribute the create sends and the read cannot see comes back as a diff
//     that never converges.
//  3. import the record and compare it attribute by attribute against the
//     state the apply produced. Anything create knows and read does not shows
//     up here as a mismatch.
//  4. apply a changed configuration and check the change actually landed.
//     Every jambonz update is a whole-record PUT, and one that quietly drops a
//     property answers 204 either way.
package provider

import (
	"context"
	"fmt"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

func TestAccAccount(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProviderFactories,
		CheckDestroy:             testAccCheckAccountDestroyed,
		Steps: []resource.TestStep{
			{
				Config: testAccConfigAccount,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("jambonz_account.test", "account_sid"),
				),
			},
			{
				ResourceName:      "jambonz_account.test",
				ImportState:       true,
				ImportStateVerify: true,
				ImportStateIdFunc: testAccImportIDAccount,
				// This resource has no "id" attribute — the framework does not
				// invent one, and the import ID is the account_sid.
				ImportStateVerifyIdentifierAttribute: "account_sid",
			},
			{
				Config: testAccConfigAccountUpdated,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("jambonz_account.test", "name", "tf-acc-account-renamed"),
				),
			},
		},
	})
}

const testAccConfigAccount = `

resource "jambonz_account" "test" {
  name                 = "tf-acc-account"
  service_provider_sid = "2708b1b3-2736-40ea-b502-c53d8396247f"
}
`

const testAccConfigAccountUpdated = `

resource "jambonz_account" "test" {
  name                 = "tf-acc-account-renamed"
  service_provider_sid = "2708b1b3-2736-40ea-b502-c53d8396247f"
}
`

// The import ID is the account_sid, which the framework does not mirror
// into the implicit "id" the test helper reads by default.
func testAccImportIDAccount(s *terraform.State) (string, error) {
	rs, ok := s.RootModule().Resources["jambonz_account.test"]
	if !ok {
		return "", fmt.Errorf("jambonz_account.test not in state")
	}
	return rs.Primary.Attributes["account_sid"], nil
}

// A destroy that leaves the record behind is a leak, and the next run would
// then be testing against another run's rubbish.
func testAccCheckAccountDestroyed(s *terraform.State) error {
	client, err := testAccAPIClient()
	if err != nil {
		return err
	}
	for name, rs := range s.RootModule().Resources {
		if rs.Type != "jambonz_account" {
			continue
		}
		id := rs.Primary.Attributes["account_sid"]
		api, err := client.GetAccountWithResponse(context.Background(), pathUUID(id))
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		if api.StatusCode() != http.StatusNotFound {
			return fmt.Errorf("%s: destroyed, but the API still answers %d for account_sid %s",
				name, api.StatusCode(), id)
		}
	}
	return nil
}
