// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// Sources: provider_code_spec.json for the schema, and build/openapi.tf.json for
// the wire contract — the operation names, the body property sets, the success
// statuses and the shape of each response. Both are generated from
// codegen/openapi.yaml with codegen/tooling/schemas/terraform.overlay.yaml
// applied.
//
// tfplugingen-framework generated the schema and the model type; this file is
// the CRUD glue it does not generate.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/resource_application"
)

var (
	_ resource.Resource                = (*applicationResource)(nil)
	_ resource.ResourceWithImportState = (*applicationResource)(nil)
)

func NewApplicationResource() resource.Resource { return &applicationResource{} }

type applicationResource struct {
	client *jambonzapi.ClientWithResponses
}

func (r *applicationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application"
}

func (r *applicationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resource_application.ApplicationResourceSchema(ctx)
}

func (r *applicationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	data, ok := req.ProviderData.(*providerData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *providerData")
		return
	}
	if data.API == nil {
		resp.Diagnostics.AddError(
			"Jambonz API client not configured",
			"This resource is managed through the Jambonz REST API, which needs the provider's `endpoint` and `api_key`. "+
				"Set them, or the JAMBONZ_ENDPOINT and JAMBONZ_API_KEY environment variables.",
		)
		return
	}
	r.client = data.API
}

func (r *applicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data resource_application.ApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Only the properties the create body declares are assigned, and each goes
	// through a helper that infers the field's Go type — a named enum's string
	// type, a float32, openapi_types.UUID, a pointer for anything the body treats
	// as optional. Every property the overlay marked readOnly is not a property of
	// this body at all, so server-owned values are never sent.
	body := jambonzapi.CreateApplicationJSONRequestBody{}
	setUUID(&body.AccountSid, data.AccountSid)

	if !data.CallHook.IsNull() && !data.CallHook.IsUnknown() {
		callHook := &body.CallHook
		setString(&callHook.Method, data.CallHook.Method)
		setString(&callHook.Password, data.CallHook.Password)
		setString(&callHook.Url, data.CallHook.Url)
		setString(&callHook.Username, data.CallHook.Username)
	}

	if !data.CallStatusHook.IsNull() && !data.CallStatusHook.IsUnknown() {
		callStatusHook := &body.CallStatusHook
		setString(&callStatusHook.Method, data.CallStatusHook.Method)
		setString(&callStatusHook.Password, data.CallStatusHook.Password)
		setString(&callStatusHook.Url, data.CallStatusHook.Url)
		setString(&callStatusHook.Username, data.CallStatusHook.Username)
	}

	if !data.MessagingHook.IsNull() && !data.MessagingHook.IsUnknown() {
		messagingHook := &body.MessagingHook
		setString(&messagingHook.Method, data.MessagingHook.Method)
		setString(&messagingHook.Password, data.MessagingHook.Password)
		setString(&messagingHook.Url, data.MessagingHook.Url)
		setString(&messagingHook.Username, data.MessagingHook.Username)
	}
	setString(&body.Name, data.Name)
	setInt(&body.RecordAllCalls, data.RecordAllCalls)

	api, err := r.client.CreateApplicationWithResponse(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	if api.StatusCode() != http.StatusCreated || api.JSON201 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	// This API's create answers with an acknowledgement — the new record's id and
	// nothing else — so the id is taken from it and the record is read back. That
	// second call is not belt and braces: every column the server defaulted is
	// unknown until it happens, and Terraform requires every value to be known
	// once apply returns.
	data.ApplicationSid = types.StringValue(string(api.JSON201.Sid))

	found, ok := r.fetch(ctx, &data, &resp.Diagnostics)
	if !ok {
		return
	}
	if !found {
		resp.Diagnostics.AddError(
			"Record not found after create",
			"The API acknowledged the create with id "+data.ApplicationSid.ValueString()+
				" and then answered 404 when asked for it.")
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *applicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data resource_application.ApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	found, ok := r.fetch(ctx, &data, &resp.Diagnostics)
	if !ok {
		return
	}
	// Drift detection lives or dies here. A 404 must remove the resource from
	// state, not error — otherwise a resource deleted out of band wedges every
	// subsequent plan.
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *applicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resource_application.ApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Computed attributes are unknown in an update plan, and Terraform requires
	// every value to be known once apply returns. Seeding them from prior state
	// covers anything the read below does not re-supply — a value the server
	// discloses once and then omits. The read still overwrites everything it does
	// send, so this cannot mask drift.
	if plan.ApplicationSid.IsUnknown() {
		plan.ApplicationSid = state.ApplicationSid
	}

	// The update body is not the create body. It carries what this operation's
	// schema declares and nothing else — the id is addressed in the path and the
	// overlay marks it readOnly, so it is not sent here, and this API rejects a
	// body that carries it.
	body := jambonzapi.UpdateApplicationJSONRequestBody{}
	setUUID(&body.AccountSid, plan.AccountSid)

	if !plan.CallHook.IsNull() && !plan.CallHook.IsUnknown() {
		callHook := &body.CallHook
		setString(&callHook.Method, plan.CallHook.Method)
		setString(&callHook.Password, plan.CallHook.Password)
		setString(&callHook.Url, plan.CallHook.Url)
		setString(&callHook.Username, plan.CallHook.Username)
	}

	if !plan.CallStatusHook.IsNull() && !plan.CallStatusHook.IsUnknown() {
		callStatusHook := &body.CallStatusHook
		setString(&callStatusHook.Method, plan.CallStatusHook.Method)
		setString(&callStatusHook.Password, plan.CallStatusHook.Password)
		setString(&callStatusHook.Url, plan.CallStatusHook.Url)
		setString(&callStatusHook.Username, plan.CallStatusHook.Username)
	}

	if !plan.MessagingHook.IsNull() && !plan.MessagingHook.IsUnknown() {
		messagingHook := &body.MessagingHook
		setString(&messagingHook.Method, plan.MessagingHook.Method)
		setString(&messagingHook.Password, plan.MessagingHook.Password)
		setString(&messagingHook.Url, plan.MessagingHook.Url)
		setString(&messagingHook.Username, plan.MessagingHook.Username)
	}
	setString(&body.Name, plan.Name)
	setInt(&body.RecordAllCalls, plan.RecordAllCalls)

	id := plan.ApplicationSid.ValueString()
	api, err := r.client.UpdateApplicationWithResponse(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	if api.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	// http.StatusNoContent: the update answers with no body, so state comes from a read.
	found, ok := r.fetch(ctx, &plan, &resp.Diagnostics)
	if !ok {
		return
	}
	if !found {
		resp.Diagnostics.AddError(
			"Record not found after update",
			"The API accepted the update to id "+id+" and then answered 404 when asked for it.")
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *applicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data resource_application.ApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ApplicationSid.ValueString()
	api, err := r.client.DeleteApplicationWithResponse(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	switch api.StatusCode() {
	case http.StatusNoContent, http.StatusNotFound:
		// Already gone is a successful delete.
	default:
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
	}
}

// ImportState is not optional. `terraform import` needs it, and so does upjet:
// Crossplane's external-name mechanism *is* import, and a provider without this
// method cannot be wrapped. The import ID is the application_sid:
//
//	terraform import jambonz_application.x 9d26a637-1679-471f-8da8-7150266e1254
func (r *applicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("application_sid"), req, resp)
}

// fetch reads the record addressed by data.ApplicationSid and copies it onto data.
// It reports whether the record exists, and whether the caller should carry on —
// a 404 is the first and not the second, and every other failure is neither.
func (r *applicationResource) fetch(ctx context.Context, data *resource_application.ApplicationModel, diags *diag.Diagnostics) (found, ok bool) {
	id := data.ApplicationSid.ValueString()
	api, err := r.client.GetApplicationWithResponse(ctx, id)
	if err != nil {
		diags.AddError("API error", err.Error())
		return false, false
	}
	if api.StatusCode() == http.StatusNotFound {
		return false, true
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		diags.AddError("Unexpected status", string(api.Body))
		return false, false
	}
	r.apply(ctx, data, api.JSON200, diags)
	return true, !diags.HasError()
}

// apply copies the API representation onto the Terraform model. Computed
// attributes are written unconditionally — that is what makes drift visible.
func (r *applicationResource) apply(ctx context.Context, data *resource_application.ApplicationModel, p *jambonzapi.Application, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.AccountSid = uuidValue(p.AccountSid)

	{
		callHook, d := resource_application.NewCallHookValue(
			data.CallHook.AttributeTypes(ctx),
			map[string]attr.Value{
				"method":      types.StringValue(string(p.CallHook.Method)),
				"password":    types.StringValue(string(p.CallHook.Password)),
				"url":         types.StringValue(string(p.CallHook.Url)),
				"username":    types.StringValue(string(p.CallHook.Username)),
				"webhook_sid": uuidPointerValue(p.CallHook.WebhookSid),
			},
		)
		diags.Append(d...)
		data.CallHook = callHook
	}

	{
		callStatusHook, d := resource_application.NewCallStatusHookValue(
			data.CallStatusHook.AttributeTypes(ctx),
			map[string]attr.Value{
				"method":      types.StringValue(string(p.CallStatusHook.Method)),
				"password":    types.StringValue(string(p.CallStatusHook.Password)),
				"url":         types.StringValue(string(p.CallStatusHook.Url)),
				"username":    types.StringValue(string(p.CallStatusHook.Username)),
				"webhook_sid": uuidPointerValue(p.CallStatusHook.WebhookSid),
			},
		)
		diags.Append(d...)
		data.CallStatusHook = callStatusHook
	}

	{
		messagingHook, d := resource_application.NewMessagingHookValue(
			data.MessagingHook.AttributeTypes(ctx),
			map[string]attr.Value{
				"method":      types.StringValue(string(p.MessagingHook.Method)),
				"password":    types.StringValue(string(p.MessagingHook.Password)),
				"url":         types.StringValue(string(p.MessagingHook.Url)),
				"username":    types.StringValue(string(p.MessagingHook.Username)),
				"webhook_sid": uuidPointerValue(p.MessagingHook.WebhookSid),
			},
		)
		diags.Append(d...)
		data.MessagingHook = messagingHook
	}
	data.Name = types.StringValue(string(p.Name))
	data.RecordAllCalls = types.Int64Value(int64(p.RecordAllCalls))
	data.ApplicationSid = uuidPointerValue(p.ApplicationSid)
}
