// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// Sources: provider_code_spec.json for the schema, build/openapi.tf.json for the
// wire contract, and codegen/tooling/schemas/acceptance.json for the values —
// see that file for why the values cannot come from the other two.
//
// These are acceptance tests: they need TF_ACC=1 and a live api-server, which
// test/docker-compose.yml provides and `make testacc` starts. Without TF_ACC
// they skip.
//
// What the four steps are for, in the order they run:
//
//  1. apply the MINIMUM configuration. Every optional attribute is left out,
//     so every one of them is planned as unknown, and an attribute still
//     unknown when apply returns ends the run with "provider returned invalid
//     result object after apply". This step is the whole reason the file
//     exists.
//  2. plan again and require the plan to be empty. terraform-plugin-testing
//     does this after every apply. It catches the opposite failure: an
//     attribute the create sends and the read cannot see comes back as a diff
//     that never converges.
//  3. import the record and compare it attribute by attribute against the
//     state the apply produced. Anything create knows and read does not shows
//     up here as a mismatch.
//  4. apply a changed configuration and check the change actually landed.
//     Every jambonz update is a whole-record PUT, and one that quietly drops a
//     property answers 204 either way.
package provider

import (
	"context"
	"fmt"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

func TestAccApplication(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProviderFactories,
		CheckDestroy:             testAccCheckApplicationDestroyed,
		Steps: []resource.TestStep{
			{
				Config: testAccConfigApplication,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("jambonz_application.test", "application_sid"),
				),
			},
			{
				ResourceName:      "jambonz_application.test",
				ImportState:       true,
				ImportStateVerify: true,
				ImportStateIdFunc: testAccImportIDApplication,
				// This resource has no "id" attribute — the framework does not
				// invent one, and the import ID is the application_sid.
				ImportStateVerifyIdentifierAttribute: "application_sid",
			},
			{
				Config: testAccConfigApplicationUpdated,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("jambonz_application.test", "name", "tf-acc-application-renamed"),
				),
			},
		},
	})
}

const testAccConfigApplication = `

resource "jambonz_application" "test" {
  name        = "tf-acc-application"
  account_sid = "9351f46a-678c-43f5-b8a6-d4eb58d131af"
  call_hook = {
    url = "http://example.com/call"
  }
  call_status_hook = {
    url = "http://example.com/status"
  }
}
`

const testAccConfigApplicationUpdated = `

resource "jambonz_application" "test" {
  name        = "tf-acc-application-renamed"
  account_sid = "9351f46a-678c-43f5-b8a6-d4eb58d131af"
  call_hook = {
    url = "http://example.com/call"
  }
  call_status_hook = {
    url = "http://example.com/status"
  }
}
`

// The import ID is the application_sid, which the framework does not mirror
// into the implicit "id" the test helper reads by default.
func testAccImportIDApplication(s *terraform.State) (string, error) {
	rs, ok := s.RootModule().Resources["jambonz_application.test"]
	if !ok {
		return "", fmt.Errorf("jambonz_application.test not in state")
	}
	return rs.Primary.Attributes["application_sid"], nil
}

// A destroy that leaves the record behind is a leak, and the next run would
// then be testing against another run's rubbish.
func testAccCheckApplicationDestroyed(s *terraform.State) error {
	client, err := testAccAPIClient()
	if err != nil {
		return err
	}
	for name, rs := range s.RootModule().Resources {
		if rs.Type != "jambonz_application" {
			continue
		}
		id := rs.Primary.Attributes["application_sid"]
		api, err := client.GetApplicationWithResponse(context.Background(), id)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		if api.StatusCode() != http.StatusNotFound {
			return fmt.Errorf("%s: destroyed, but the API still answers %d for application_sid %s",
				name, api.StatusCode(), id)
		}
	}
	return nil
}
