// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// A data source is one read operation. It shares the resource's binding and the
// resource's conversion fragments, so a lookup and a managed record cannot
// disagree about how a field is decoded.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/datasource_application"
)

var (
	_ datasource.DataSource              = (*applicationDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*applicationDataSource)(nil)
)

func NewApplicationDataSource() datasource.DataSource { return &applicationDataSource{} }

type applicationDataSource struct {
	client *jambonzapi.ClientWithResponses
}

func (d *applicationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application"
}

func (d *applicationDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_application.ApplicationDataSourceSchema(ctx)
}

func (d *applicationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*jambonzapi.ClientWithResponses)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *jambonzapi.ClientWithResponses")
		return
	}
	d.client = client
}

func (d *applicationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data datasource_application.ApplicationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ApplicationSid.ValueString()
	api, err := d.client.GetApplicationWithResponse(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	// Unlike a resource's read, a 404 here is an error. A data source names a
	// record the configuration depends on; silently yielding nothing would push the
	// failure into whatever referenced it.
	if api.StatusCode() == http.StatusNotFound {
		resp.Diagnostics.AddError("Not found", "no application with application_sid "+id)
		return
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	d.apply(ctx, &data, api.JSON200, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// apply copies the API representation onto the Terraform model.
func (d *applicationDataSource) apply(ctx context.Context, data *datasource_application.ApplicationModel, p *jambonzapi.Application, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.ApplicationSid = uuidPointerValue(p.ApplicationSid)
	data.AccountSid = uuidValue(p.AccountSid)

	{
		callHook, d := datasource_application.NewCallHookValue(
			data.CallHook.AttributeTypes(ctx),
			map[string]attr.Value{
				"method":      types.StringValue(string(p.CallHook.Method)),
				"password":    types.StringValue(string(p.CallHook.Password)),
				"url":         types.StringValue(string(p.CallHook.Url)),
				"username":    types.StringValue(string(p.CallHook.Username)),
				"webhook_sid": uuidPointerValue(p.CallHook.WebhookSid),
			},
		)
		diags.Append(d...)
		data.CallHook = callHook
	}

	{
		callStatusHook, d := datasource_application.NewCallStatusHookValue(
			data.CallStatusHook.AttributeTypes(ctx),
			map[string]attr.Value{
				"method":      types.StringValue(string(p.CallStatusHook.Method)),
				"password":    types.StringValue(string(p.CallStatusHook.Password)),
				"url":         types.StringValue(string(p.CallStatusHook.Url)),
				"username":    types.StringValue(string(p.CallStatusHook.Username)),
				"webhook_sid": uuidPointerValue(p.CallStatusHook.WebhookSid),
			},
		)
		diags.Append(d...)
		data.CallStatusHook = callStatusHook
	}

	{
		messagingHook, d := datasource_application.NewMessagingHookValue(
			data.MessagingHook.AttributeTypes(ctx),
			map[string]attr.Value{
				"method":      types.StringValue(string(p.MessagingHook.Method)),
				"password":    types.StringValue(string(p.MessagingHook.Password)),
				"url":         types.StringValue(string(p.MessagingHook.Url)),
				"username":    types.StringValue(string(p.MessagingHook.Username)),
				"webhook_sid": uuidPointerValue(p.MessagingHook.WebhookSid),
			},
		)
		diags.Append(d...)
		data.MessagingHook = messagingHook
	}
	data.Name = types.StringValue(string(p.Name))
	data.RecordAllCalls = types.Int64Value(int64(p.RecordAllCalls))
}
