// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// A data source is one read operation. It shares the resource's binding and the
// resource's conversion fragments, so a lookup and a managed record cannot
// disagree about how a field is decoded.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/datasource_phone_number"
)

var (
	_ datasource.DataSource              = (*phoneNumberDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*phoneNumberDataSource)(nil)
)

func NewPhoneNumberDataSource() datasource.DataSource { return &phoneNumberDataSource{} }

type phoneNumberDataSource struct {
	client *jambonzapi.ClientWithResponses
}

func (d *phoneNumberDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_phone_number"
}

func (d *phoneNumberDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_phone_number.PhoneNumberDataSourceSchema(ctx)
}

func (d *phoneNumberDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*jambonzapi.ClientWithResponses)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *jambonzapi.ClientWithResponses")
		return
	}
	d.client = client
}

func (d *phoneNumberDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data datasource_phone_number.PhoneNumberModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.PhoneNumberSid.ValueString()
	api, err := d.client.GetPhoneNumberWithResponse(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	// Unlike a resource's read, a 404 here is an error. A data source names a
	// record the configuration depends on; silently yielding nothing would push the
	// failure into whatever referenced it.
	if api.StatusCode() == http.StatusNotFound {
		resp.Diagnostics.AddError("Not found", "no phone_number with phone_number_sid "+id)
		return
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	d.apply(ctx, &data, api.JSON200, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// apply copies the API representation onto the Terraform model.
func (d *phoneNumberDataSource) apply(ctx context.Context, data *datasource_phone_number.PhoneNumberModel, p *jambonzapi.PhoneNumber, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.PhoneNumberSid = uuidPointerValue(p.PhoneNumberSid)
	data.AccountSid = uuidPointerValue(p.AccountSid)
	data.ApplicationSid = uuidPointerValue(p.ApplicationSid)
	data.Number = types.StringValue(string(p.Number))
	data.VoipCarrierSid = uuidValue(p.VoipCarrierSid)
	_ = ctx
	_ = diags
}
