// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// Sources: provider_code_spec.json for the schema, build/openapi.tf.json for the
// wire contract, and codegen/tooling/schemas/acceptance.json for the values —
// see that file for why the values cannot come from the other two.
//
// These are acceptance tests: they need TF_ACC=1 and a live api-server, which
// test/docker-compose.yml provides and `make testacc` starts. Without TF_ACC
// they skip.
//
// What the four steps are for, in the order they run:
//
//  1. apply the MINIMUM configuration. Every optional attribute is left out,
//     so every one of them is planned as unknown, and an attribute still
//     unknown when apply returns ends the run with "provider returned invalid
//     result object after apply". This step is the whole reason the file
//     exists.
//  2. plan again and require the plan to be empty. terraform-plugin-testing
//     does this after every apply. It catches the opposite failure: an
//     attribute the create sends and the read cannot see comes back as a diff
//     that never converges.
//  3. import the record and compare it attribute by attribute against the
//     state the apply produced. Anything create knows and read does not shows
//     up here as a mismatch.
//  4. apply a changed configuration and check the change actually landed.
//     Every jambonz update is a whole-record PUT, and one that quietly drops a
//     property answers 204 either way.
package provider

import (
	"context"
	"fmt"
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

func TestAccPhoneNumber(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProviderFactories,
		CheckDestroy:             testAccCheckPhoneNumberDestroyed,
		Steps: []resource.TestStep{
			{
				Config: testAccConfigPhoneNumber,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("jambonz_phone_number.test", "phone_number_sid"),
				),
			},
			{
				ResourceName:      "jambonz_phone_number.test",
				ImportState:       true,
				ImportStateVerify: true,
				ImportStateIdFunc: testAccImportIDPhoneNumber,
				// This resource has no "id" attribute — the framework does not
				// invent one, and the import ID is the phone_number_sid.
				ImportStateVerifyIdentifierAttribute: "phone_number_sid",
			},
			{
				Config: testAccConfigPhoneNumberUpdated,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("jambonz_phone_number.test", "number", "15551230002"),
				),
			},
		},
	})
}

const testAccConfigPhoneNumber = `
resource "jambonz_voip_carrier" "acc" {
  name = "tf-acc-carrier-for-number"
}

resource "jambonz_phone_number" "test" {
  number           = "15551230001"
  voip_carrier_sid = jambonz_voip_carrier.acc.voip_carrier_sid
}
`

const testAccConfigPhoneNumberUpdated = `
resource "jambonz_voip_carrier" "acc" {
  name = "tf-acc-carrier-for-number"
}

resource "jambonz_phone_number" "test" {
  number           = "15551230002"
  voip_carrier_sid = jambonz_voip_carrier.acc.voip_carrier_sid
}
`

// The import ID is the phone_number_sid, which the framework does not mirror
// into the implicit "id" the test helper reads by default.
func testAccImportIDPhoneNumber(s *terraform.State) (string, error) {
	rs, ok := s.RootModule().Resources["jambonz_phone_number.test"]
	if !ok {
		return "", fmt.Errorf("jambonz_phone_number.test not in state")
	}
	return rs.Primary.Attributes["phone_number_sid"], nil
}

// A destroy that leaves the record behind is a leak, and the next run would
// then be testing against another run's rubbish.
func testAccCheckPhoneNumberDestroyed(s *terraform.State) error {
	client, err := testAccAPIClient()
	if err != nil {
		return err
	}
	for name, rs := range s.RootModule().Resources {
		if rs.Type != "jambonz_phone_number" {
			continue
		}
		id := rs.Primary.Attributes["phone_number_sid"]
		api, err := client.GetPhoneNumberWithResponse(context.Background(), id)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		if api.StatusCode() != http.StatusNotFound {
			return fmt.Errorf("%s: destroyed, but the API still answers %d for phone_number_sid %s",
				name, api.StatusCode(), id)
		}
	}
	return nil
}
