// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// Sources: provider_code_spec.json for the schema, and build/openapi.tf.json for
// the wire contract — the operation names, the body property sets, the success
// statuses and the shape of each response. Both are generated from
// codegen/openapi.yaml with codegen/tooling/schemas/terraform.overlay.yaml
// applied.
//
// tfplugingen-framework generated the schema and the model type; this file is
// the CRUD glue it does not generate.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/resource_phone_number"
)

var (
	_ resource.Resource                = (*phoneNumberResource)(nil)
	_ resource.ResourceWithImportState = (*phoneNumberResource)(nil)
	_ resource.ResourceWithModifyPlan  = (*phoneNumberResource)(nil)
)

func NewPhoneNumberResource() resource.Resource { return &phoneNumberResource{} }

type phoneNumberResource struct {
	client *jambonzapi.ClientWithResponses
}

func (r *phoneNumberResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_phone_number"
}

func (r *phoneNumberResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resource_phone_number.PhoneNumberResourceSchema(ctx)
}

func (r *phoneNumberResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	data, ok := req.ProviderData.(*providerData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *providerData")
		return
	}
	if data.API == nil {
		resp.Diagnostics.AddError(
			"Jambonz API client not configured",
			"This resource is managed through the Jambonz REST API, which needs the provider's `endpoint` and `api_key`. "+
				"Set them, or the JAMBONZ_ENDPOINT and JAMBONZ_API_KEY environment variables.",
		)
		return
	}
	r.client = data.API
}

func (r *phoneNumberResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data resource_phone_number.PhoneNumberModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Only the properties the create body declares are assigned, and each goes
	// through a helper that infers the field's Go type — a named enum's string
	// type, a float32, openapi_types.UUID, a pointer for anything the body treats
	// as optional. Every property the overlay marked readOnly is not a property of
	// this body at all, so server-owned values are never sent.
	body := jambonzapi.CreatePhoneNumberJSONRequestBody{}
	setUUID(&body.AccountSid, data.AccountSid)
	setUUIDPtr(&body.ApplicationSid, data.ApplicationSid)
	setString(&body.Number, data.Number)
	setUUID(&body.VoipCarrierSid, data.VoipCarrierSid)

	api, err := r.client.CreatePhoneNumberWithResponse(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	if api.StatusCode() != http.StatusCreated || api.JSON201 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	// This API's create answers with an acknowledgement — the new record's id and
	// nothing else — so the id is taken from it and the record is read back. That
	// second call is not belt and braces: every column the server defaulted is
	// unknown until it happens, and Terraform requires every value to be known
	// once apply returns.
	data.PhoneNumberSid = types.StringValue(string(api.JSON201.Sid))

	found, ok := r.fetch(ctx, &data, &resp.Diagnostics)
	if !ok {
		return
	}
	if !found {
		resp.Diagnostics.AddError(
			"Record not found after create",
			"The API acknowledged the create with id "+data.PhoneNumberSid.ValueString()+
				" and then answered 404 when asked for it.")
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *phoneNumberResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data resource_phone_number.PhoneNumberModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	found, ok := r.fetch(ctx, &data, &resp.Diagnostics)
	if !ok {
		return
	}
	// Drift detection lives or dies here. A 404 must remove the resource from
	// state, not error — otherwise a resource deleted out of band wedges every
	// subsequent plan.
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *phoneNumberResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resource_phone_number.PhoneNumberModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Computed attributes are unknown in an update plan, and Terraform requires
	// every value to be known once apply returns. Seeding them from prior state
	// covers anything the read below does not re-supply — a value the server
	// discloses once and then omits. The read still overwrites everything it does
	// send, so this cannot mask drift.
	if plan.PhoneNumberSid.IsUnknown() {
		plan.PhoneNumberSid = state.PhoneNumberSid
	}

	// The update body is not the create body. It carries what this operation's
	// schema declares and nothing else — the id is addressed in the path and the
	// overlay marks it readOnly, so it is not sent here, and this API rejects a
	// body that carries it.
	body := jambonzapi.UpdatePhoneNumberJSONRequestBody{}
	setUUID(&body.AccountSid, plan.AccountSid)
	setUUID(&body.ApplicationSid, plan.ApplicationSid)

	id := plan.PhoneNumberSid.ValueString()
	api, err := r.client.UpdatePhoneNumberWithResponse(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	if api.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	// http.StatusNoContent: the update answers with no body, so state comes from a read.
	found, ok := r.fetch(ctx, &plan, &resp.Diagnostics)
	if !ok {
		return
	}
	if !found {
		resp.Diagnostics.AddError(
			"Record not found after update",
			"The API accepted the update to id "+id+" and then answered 404 when asked for it.")
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *phoneNumberResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data resource_phone_number.PhoneNumberModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.PhoneNumberSid.ValueString()
	api, err := r.client.DeletePhoneNumberWithResponse(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	switch api.StatusCode() {
	case http.StatusNoContent, http.StatusNotFound:
		// Already gone is a successful delete.
	default:
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
	}
}

// ImportState is not optional. `terraform import` needs it, and so does upjet:
// Crossplane's external-name mechanism *is* import, and a provider without this
// method cannot be wrapped. The import ID is the phone_number_sid:
//
//	terraform import jambonz_phone_number.x 9d26a637-1679-471f-8da8-7150266e1254
func (r *phoneNumberResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("phone_number_sid"), req, resp)
}

// ModifyPlan forces replacement for the attributes the create body accepts and
// the update body does not.
//
// Without it those attributes are settable, and changing one plans as an in-place
// update that sends a body with no such property — the API stores nothing, the
// apply reports success, and the next read shows the old value back. Which
// attributes these are is not a judgement: it is the difference between the two
// bodies, read from the spec.
func (r *phoneNumberResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	// Nothing to force on a create (no state) or a destroy (no plan).
	if req.State.Raw.IsNull() || req.Plan.Raw.IsNull() {
		return
	}
	var plan, state resource_phone_number.PhoneNumberModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !plan.Number.Equal(state.Number) {
		resp.RequiresReplace = append(resp.RequiresReplace, path.Root("number"))
	}
	if !plan.VoipCarrierSid.Equal(state.VoipCarrierSid) {
		resp.RequiresReplace = append(resp.RequiresReplace, path.Root("voip_carrier_sid"))
	}
}

// fetch reads the record addressed by data.PhoneNumberSid and copies it onto data.
// It reports whether the record exists, and whether the caller should carry on —
// a 404 is the first and not the second, and every other failure is neither.
func (r *phoneNumberResource) fetch(ctx context.Context, data *resource_phone_number.PhoneNumberModel, diags *diag.Diagnostics) (found, ok bool) {
	id := data.PhoneNumberSid.ValueString()
	api, err := r.client.GetPhoneNumberWithResponse(ctx, id)
	if err != nil {
		diags.AddError("API error", err.Error())
		return false, false
	}
	if api.StatusCode() == http.StatusNotFound {
		return false, true
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		diags.AddError("Unexpected status", string(api.Body))
		return false, false
	}
	r.apply(ctx, data, api.JSON200, diags)
	return true, !diags.HasError()
}

// apply copies the API representation onto the Terraform model. Computed
// attributes are written unconditionally — that is what makes drift visible.
func (r *phoneNumberResource) apply(ctx context.Context, data *resource_phone_number.PhoneNumberModel, p *jambonzapi.PhoneNumber, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.AccountSid = uuidPointerValue(p.AccountSid)
	data.ApplicationSid = uuidPointerValue(p.ApplicationSid)
	data.Number = types.StringValue(string(p.Number))
	data.VoipCarrierSid = uuidValue(p.VoipCarrierSid)
	data.PhoneNumberSid = uuidPointerValue(p.PhoneNumberSid)
	_ = ctx
	_ = diags
}
