// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// A data source is one read operation. It shares the resource's binding and the
// resource's conversion fragments, so a lookup and a managed record cannot
// disagree about how a field is decoded.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/datasource_sip_gateway"
)

var (
	_ datasource.DataSource              = (*sipGatewayDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*sipGatewayDataSource)(nil)
)

func NewSipGatewayDataSource() datasource.DataSource { return &sipGatewayDataSource{} }

type sipGatewayDataSource struct {
	client *jambonzapi.ClientWithResponses
}

func (d *sipGatewayDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sip_gateway"
}

func (d *sipGatewayDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_sip_gateway.SipGatewayDataSourceSchema(ctx)
}

func (d *sipGatewayDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*jambonzapi.ClientWithResponses)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *jambonzapi.ClientWithResponses")
		return
	}
	d.client = client
}

func (d *sipGatewayDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data datasource_sip_gateway.SipGatewayModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.SipGatewaySid.ValueString()
	api, err := d.client.GetSipGatewayWithResponse(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	// Unlike a resource's read, a 404 here is an error. A data source names a
	// record the configuration depends on; silently yielding nothing would push the
	// failure into whatever referenced it.
	if api.StatusCode() == http.StatusNotFound {
		resp.Diagnostics.AddError("Not found", "no sip_gateway with sip_gateway_sid "+id)
		return
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	d.apply(ctx, &data, api.JSON200, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// apply copies the API representation onto the Terraform model.
func (d *sipGatewayDataSource) apply(ctx context.Context, data *datasource_sip_gateway.SipGatewayModel, p *jambonzapi.SipGateway, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.SipGatewaySid = uuidPointerValue(p.SipGatewaySid)
	data.Inbound = types.BoolPointerValue((*bool)(p.Inbound))
	data.Ipv4 = types.StringValue(string(p.Ipv4))
	data.Netmask = floatValue(p.Netmask)
	data.Outbound = types.BoolPointerValue((*bool)(p.Outbound))
	data.Port = floatValue(p.Port)
	data.VoipCarrierSid = uuidValue(p.VoipCarrierSid)
	_ = ctx
	_ = diags
}
