// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// Sources: provider_code_spec.json for the schema, and build/openapi.tf.json for
// the wire contract — the operation names, the body property sets, the success
// statuses and the shape of each response. Both are generated from
// codegen/openapi.yaml with codegen/tooling/schemas/terraform.overlay.yaml
// applied.
//
// tfplugingen-framework generated the schema and the model type; this file is
// the CRUD glue it does not generate.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/resource_voip_carrier"
)

var (
	_ resource.Resource                = (*voipCarrierResource)(nil)
	_ resource.ResourceWithImportState = (*voipCarrierResource)(nil)
)

func NewVoipCarrierResource() resource.Resource { return &voipCarrierResource{} }

type voipCarrierResource struct {
	client *jambonzapi.ClientWithResponses
}

func (r *voipCarrierResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_voip_carrier"
}

func (r *voipCarrierResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resource_voip_carrier.VoipCarrierResourceSchema(ctx)
}

func (r *voipCarrierResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	data, ok := req.ProviderData.(*providerData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *providerData")
		return
	}
	if data.API == nil {
		resp.Diagnostics.AddError(
			"Jambonz API client not configured",
			"This resource is managed through the Jambonz REST API, which needs the provider's `endpoint` and `api_key`. "+
				"Set them, or the JAMBONZ_ENDPOINT and JAMBONZ_API_KEY environment variables.",
		)
		return
	}
	r.client = data.API
}

func (r *voipCarrierResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data resource_voip_carrier.VoipCarrierModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Only the properties the create body declares are assigned, and each goes
	// through a helper that infers the field's Go type — a named enum's string
	// type, a float32, openapi_types.UUID, a pointer for anything the body treats
	// as optional. Every property the overlay marked readOnly is not a property of
	// this body at all, so server-owned values are never sent.
	body := jambonzapi.CreateVoipCarrierJSONRequestBody{}
	setStringPtr(&body.AccountSid, data.AccountSid)
	setStringPtr(&body.ApplicationSid, data.ApplicationSid)
	setStringPtr(&body.Description, data.Description)
	setStringPtr(&body.Diversion, data.Diversion)
	setIntPtr(&body.E164LeadingPlus, data.E164LeadingPlus)
	setStringPtr(&body.InboundAuthPassword, data.InboundAuthPassword)
	setStringPtr(&body.InboundAuthUsername, data.InboundAuthUsername)
	setIntPtr(&body.IsActive, data.IsActive)
	setString(&body.Name, data.Name)
	setStringPtr(&body.RegisterFromDomain, data.RegisterFromDomain)
	setStringPtr(&body.RegisterFromUser, data.RegisterFromUser)
	setStringPtr(&body.RegisterPassword, data.RegisterPassword)
	setIntPtr(&body.RegisterPublicIpInContact, data.RegisterPublicIpInContact)
	setStringPtr(&body.RegisterSipRealm, data.RegisterSipRealm)
	setIntPtr(&body.RegisterUseTls, data.RegisterUseTls)
	setStringPtr(&body.RegisterUsername, data.RegisterUsername)
	setIntPtr(&body.RequiresRegister, data.RequiresRegister)
	setStringPtr(&body.TechPrefix, data.TechPrefix)

	api, err := r.client.CreateVoipCarrierWithResponse(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	if api.StatusCode() != http.StatusCreated || api.JSON201 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	// This API's create answers with an acknowledgement — the new record's id and
	// nothing else — so the id is taken from it and the record is read back. That
	// second call is not belt and braces: every column the server defaulted is
	// unknown until it happens, and Terraform requires every value to be known
	// once apply returns.
	data.VoipCarrierSid = types.StringValue(string(api.JSON201.Sid))

	found, ok := r.fetch(ctx, &data, &resp.Diagnostics)
	if !ok {
		return
	}
	if !found {
		resp.Diagnostics.AddError(
			"Record not found after create",
			"The API acknowledged the create with id "+data.VoipCarrierSid.ValueString()+
				" and then answered 404 when asked for it.")
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *voipCarrierResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data resource_voip_carrier.VoipCarrierModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	found, ok := r.fetch(ctx, &data, &resp.Diagnostics)
	if !ok {
		return
	}
	// Drift detection lives or dies here. A 404 must remove the resource from
	// state, not error — otherwise a resource deleted out of band wedges every
	// subsequent plan.
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *voipCarrierResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resource_voip_carrier.VoipCarrierModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Computed attributes are unknown in an update plan, and Terraform requires
	// every value to be known once apply returns. Seeding them from prior state
	// covers anything the read below does not re-supply — a value the server
	// discloses once and then omits. The read still overwrites everything it does
	// send, so this cannot mask drift.
	if plan.VoipCarrierSid.IsUnknown() {
		plan.VoipCarrierSid = state.VoipCarrierSid
	}

	// The update body is not the create body. It carries what this operation's
	// schema declares and nothing else — the id is addressed in the path and the
	// overlay marks it readOnly, so it is not sent here, and this API rejects a
	// body that carries it.
	body := jambonzapi.UpdateVoipCarrierJSONRequestBody{}
	setUUIDPtr(&body.AccountSid, plan.AccountSid)
	setUUIDPtr(&body.ApplicationSid, plan.ApplicationSid)
	setStringPtr(&body.Description, plan.Description)
	setStringPtr(&body.Diversion, plan.Diversion)
	setIntPtr(&body.E164LeadingPlus, plan.E164LeadingPlus)
	setStringPtr(&body.InboundAuthPassword, plan.InboundAuthPassword)
	setStringPtr(&body.InboundAuthUsername, plan.InboundAuthUsername)
	setIntPtr(&body.IsActive, plan.IsActive)
	setString(&body.Name, plan.Name)
	setStringPtr(&body.RegisterFromDomain, plan.RegisterFromDomain)
	setStringPtr(&body.RegisterFromUser, plan.RegisterFromUser)
	setStringPtr(&body.RegisterPassword, plan.RegisterPassword)
	setIntPtr(&body.RegisterPublicIpInContact, plan.RegisterPublicIpInContact)
	setStringPtr(&body.RegisterSipRealm, plan.RegisterSipRealm)
	setIntPtr(&body.RegisterUseTls, plan.RegisterUseTls)
	setStringPtr(&body.RegisterUsername, plan.RegisterUsername)
	setIntPtr(&body.RequiresRegister, plan.RequiresRegister)
	setStringPtr(&body.TechPrefix, plan.TechPrefix)

	id := plan.VoipCarrierSid.ValueString()
	api, err := r.client.UpdateVoipCarrierWithResponse(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	if api.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	// http.StatusNoContent: the update answers with no body, so state comes from a read.
	found, ok := r.fetch(ctx, &plan, &resp.Diagnostics)
	if !ok {
		return
	}
	if !found {
		resp.Diagnostics.AddError(
			"Record not found after update",
			"The API accepted the update to id "+id+" and then answered 404 when asked for it.")
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *voipCarrierResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data resource_voip_carrier.VoipCarrierModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.VoipCarrierSid.ValueString()
	api, err := r.client.DeleteVoipCarrierWithResponse(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	switch api.StatusCode() {
	case http.StatusNoContent, http.StatusNotFound:
		// Already gone is a successful delete.
	default:
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
	}
}

// ImportState is not optional. `terraform import` needs it, and so does upjet:
// Crossplane's external-name mechanism *is* import, and a provider without this
// method cannot be wrapped. The import ID is the voip_carrier_sid:
//
//	terraform import jambonz_voip_carrier.x 9d26a637-1679-471f-8da8-7150266e1254
func (r *voipCarrierResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("voip_carrier_sid"), req, resp)
}

// fetch reads the record addressed by data.VoipCarrierSid and copies it onto data.
// It reports whether the record exists, and whether the caller should carry on —
// a 404 is the first and not the second, and every other failure is neither.
func (r *voipCarrierResource) fetch(ctx context.Context, data *resource_voip_carrier.VoipCarrierModel, diags *diag.Diagnostics) (found, ok bool) {
	id := data.VoipCarrierSid.ValueString()
	api, err := r.client.GetVoipCarrierWithResponse(ctx, id)
	if err != nil {
		diags.AddError("API error", err.Error())
		return false, false
	}
	if api.StatusCode() == http.StatusNotFound {
		return false, true
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		diags.AddError("Unexpected status", string(api.Body))
		return false, false
	}
	r.apply(ctx, data, api.JSON200, diags)
	return true, !diags.HasError()
}

// apply copies the API representation onto the Terraform model. Computed
// attributes are written unconditionally — that is what makes drift visible.
func (r *voipCarrierResource) apply(ctx context.Context, data *resource_voip_carrier.VoipCarrierModel, p *jambonzapi.VoipCarrier, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.AccountSid = uuidPointerValue(p.AccountSid)
	data.ApplicationSid = uuidPointerValue(p.ApplicationSid)
	data.Description = types.StringPointerValue((*string)(p.Description))
	data.Diversion = types.StringPointerValue((*string)(p.Diversion))
	data.E164LeadingPlus = int64PointerValue(p.E164LeadingPlus)
	data.InboundAuthUsername = types.StringPointerValue((*string)(p.InboundAuthUsername))
	data.IsActive = int64PointerValue(p.IsActive)
	data.Name = types.StringValue(string(p.Name))
	data.RegisterFromDomain = types.StringPointerValue((*string)(p.RegisterFromDomain))
	data.RegisterFromUser = types.StringPointerValue((*string)(p.RegisterFromUser))
	data.RegisterPublicIpInContact = int64PointerValue(p.RegisterPublicIpInContact)
	data.RegisterSipRealm = types.StringPointerValue((*string)(p.RegisterSipRealm))
	data.RegisterUseTls = int64PointerValue(p.RegisterUseTls)
	data.RegisterUsername = types.StringPointerValue((*string)(p.RegisterUsername))
	data.RequiresRegister = int64PointerValue(p.RequiresRegister)
	data.TechPrefix = types.StringPointerValue((*string)(p.TechPrefix))
	data.VoipCarrierSid = uuidPointerValue(p.VoipCarrierSid)

	// inbound_auth_password is sensitive. An API that returns a secret once, at create, omits
	// it on every subsequent read; overwriting with null would show a spurious diff
	// forever — so it is only written when the server actually sent one.
	if p.InboundAuthPassword != nil {
		data.InboundAuthPassword = types.StringPointerValue((*string)(p.InboundAuthPassword))
	}

	// register_password is sensitive. An API that returns a secret once, at create, omits
	// it on every subsequent read; overwriting with null would show a spurious diff
	// forever — so it is only written when the server actually sent one.
	if p.RegisterPassword != nil {
		data.RegisterPassword = types.StringPointerValue((*string)(p.RegisterPassword))
	}
	_ = ctx
	_ = diags
}
