// Code generated by codegen/tooling/cmd/gen. DO NOT EDIT.
//
// A data source is one read operation. It shares the resource's binding and the
// resource's conversion fragments, so a lookup and a managed record cannot
// disagree about how a field is decoded.
//
// Committed so the pipeline's output is reviewable in a pull request — `make
// verify` regenerates it and fails if this file and the spec disagree.
package provider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"terraform-provider-jambonz/internal/api/jambonzapi"
	"terraform-provider-jambonz/internal/datasource_voip_carrier"
)

var (
	_ datasource.DataSource              = (*voipCarrierDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*voipCarrierDataSource)(nil)
)

func NewVoipCarrierDataSource() datasource.DataSource { return &voipCarrierDataSource{} }

type voipCarrierDataSource struct {
	client *jambonzapi.ClientWithResponses
}

func (d *voipCarrierDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_voip_carrier"
}

func (d *voipCarrierDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_voip_carrier.VoipCarrierDataSourceSchema(ctx)
}

func (d *voipCarrierDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	data, ok := req.ProviderData.(*providerData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", "expected *providerData")
		return
	}
	if data.API == nil {
		resp.Diagnostics.AddError(
			"Jambonz API client not configured",
			"This data source is managed through the Jambonz REST API, which needs the provider's `endpoint` and `api_key`. "+
				"Set them, or the JAMBONZ_ENDPOINT and JAMBONZ_API_KEY environment variables.",
		)
		return
	}
	d.client = data.API
}

func (d *voipCarrierDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data datasource_voip_carrier.VoipCarrierModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := data.VoipCarrierSid.ValueString()
	api, err := d.client.GetVoipCarrierWithResponse(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("API error", err.Error())
		return
	}
	// Unlike a resource's read, a 404 here is an error. A data source names a
	// record the configuration depends on; silently yielding nothing would push the
	// failure into whatever referenced it.
	if api.StatusCode() == http.StatusNotFound {
		resp.Diagnostics.AddError("Not found", "no voip_carrier with voip_carrier_sid "+id)
		return
	}
	if api.StatusCode() != http.StatusOK || api.JSON200 == nil {
		resp.Diagnostics.AddError("Unexpected status", string(api.Body))
		return
	}

	d.apply(ctx, &data, api.JSON200, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// apply copies the API representation onto the Terraform model.
func (d *voipCarrierDataSource) apply(ctx context.Context, data *datasource_voip_carrier.VoipCarrierModel, p *jambonzapi.VoipCarrier, diags *diag.Diagnostics) {
	if p == nil {
		return
	}
	data.VoipCarrierSid = uuidPointerValue(p.VoipCarrierSid)
	data.AccountSid = uuidPointerValue(p.AccountSid)
	data.ApplicationSid = uuidPointerValue(p.ApplicationSid)
	data.Description = types.StringPointerValue((*string)(p.Description))
	data.Diversion = types.StringPointerValue((*string)(p.Diversion))
	data.E164LeadingPlus = int64PointerValue(p.E164LeadingPlus)
	data.InboundAuthPassword = types.StringPointerValue((*string)(p.InboundAuthPassword))
	data.InboundAuthUsername = types.StringPointerValue((*string)(p.InboundAuthUsername))
	data.IsActive = int64PointerValue(p.IsActive)
	data.Name = types.StringValue(string(p.Name))
	data.RegisterFromDomain = types.StringPointerValue((*string)(p.RegisterFromDomain))
	data.RegisterFromUser = types.StringPointerValue((*string)(p.RegisterFromUser))
	data.RegisterPassword = types.StringPointerValue((*string)(p.RegisterPassword))
	data.RegisterPublicIpInContact = int64PointerValue(p.RegisterPublicIpInContact)
	data.RegisterSipRealm = types.StringPointerValue((*string)(p.RegisterSipRealm))
	data.RegisterUseTls = int64PointerValue(p.RegisterUseTls)
	data.RegisterUsername = types.StringPointerValue((*string)(p.RegisterUsername))
	data.RequiresRegister = int64PointerValue(p.RequiresRegister)
	data.TechPrefix = types.StringPointerValue((*string)(p.TechPrefix))
	_ = ctx
	_ = diags
}
