// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_voip_carrier

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func VoipCarrierResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_sid": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"application_sid": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"diversion": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Diversion header or phone number to apply to outbound calls",
				MarkdownDescription: "Diversion header or phone number to apply to outbound calls",
			},
			"e164_leading_plus": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "whether a leading + is required on INVITEs to this provider",
				MarkdownDescription: "whether a leading + is required on INVITEs to this provider",
			},
			"inbound_auth_password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "challenge inbound calls with this username/password if supplied",
				MarkdownDescription: "challenge inbound calls with this username/password if supplied",
			},
			"inbound_auth_username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "challenge inbound calls with this username/password if supplied",
				MarkdownDescription: "challenge inbound calls with this username/password if supplied",
			},
			"is_active": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "voip carrier name",
				MarkdownDescription: "voip carrier name",
			},
			"register_from_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "optional domain to apply in From header",
				MarkdownDescription: "optional domain to apply in From header",
			},
			"register_from_user": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "optional username to apply in From header",
				MarkdownDescription: "optional username to apply in From header",
			},
			"register_password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "sip password to authenticate with, if registration is required",
				MarkdownDescription: "sip password to authenticate with, if registration is required",
			},
			"register_public_ip_in_contact": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "if true, use our public ip in Contact header; otherwise, use sip realm",
				MarkdownDescription: "if true, use our public ip in Contact header; otherwise, use sip realm",
			},
			"register_sip_realm": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "sip realm to authenticate with, if registration is required",
				MarkdownDescription: "sip realm to authenticate with, if registration is required",
			},
			"register_use_tls": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "wehther this provider requires us to send a REGISTER use TLS protocol",
				MarkdownDescription: "wehther this provider requires us to send a REGISTER use TLS protocol",
			},
			"register_username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "sip username to authenticate with, if registration is required",
				MarkdownDescription: "sip username to authenticate with, if registration is required",
			},
			"requires_register": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "wehther this provider requires us to send a REGISTER to them in order to receive calls",
				MarkdownDescription: "wehther this provider requires us to send a REGISTER to them in order to receive calls",
			},
			"service_provider_sid": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"tech_prefix": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "prefix to be applied to the called number for outbound call attempts",
				MarkdownDescription: "prefix to be applied to the called number for outbound call attempts",
			},
			"voip_carrier_sid": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type VoipCarrierModel struct {
	AccountSid                types.String `tfsdk:"account_sid"`
	ApplicationSid            types.String `tfsdk:"application_sid"`
	Description               types.String `tfsdk:"description"`
	Diversion                 types.String `tfsdk:"diversion"`
	E164LeadingPlus           types.Int64  `tfsdk:"e164_leading_plus"`
	InboundAuthPassword       types.String `tfsdk:"inbound_auth_password"`
	InboundAuthUsername       types.String `tfsdk:"inbound_auth_username"`
	IsActive                  types.Int64  `tfsdk:"is_active"`
	Name                      types.String `tfsdk:"name"`
	RegisterFromDomain        types.String `tfsdk:"register_from_domain"`
	RegisterFromUser          types.String `tfsdk:"register_from_user"`
	RegisterPassword          types.String `tfsdk:"register_password"`
	RegisterPublicIpInContact types.Int64  `tfsdk:"register_public_ip_in_contact"`
	RegisterSipRealm          types.String `tfsdk:"register_sip_realm"`
	RegisterUseTls            types.Int64  `tfsdk:"register_use_tls"`
	RegisterUsername          types.String `tfsdk:"register_username"`
	RequiresRegister          types.Int64  `tfsdk:"requires_register"`
	ServiceProviderSid        types.String `tfsdk:"service_provider_sid"`
	TechPrefix                types.String `tfsdk:"tech_prefix"`
	VoipCarrierSid            types.String `tfsdk:"voip_carrier_sid"`
}
