// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_application

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ApplicationResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_sid": schema.StringAttribute{
				Required: true,
			},
			"application_sid": schema.StringAttribute{
				Computed: true,
			},
			"call_hook": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"method": schema.StringAttribute{
						Optional: true,
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"GET",
								"POST",
							),
						},
						Default: stringdefault.StaticString("POST"),
					},
					"password": schema.StringAttribute{
						Required:  true,
						Sensitive: true,
					},
					"url": schema.StringAttribute{
						Required: true,
					},
					"username": schema.StringAttribute{
						Required: true,
					},
					"webhook_sid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: CallHookType{
					ObjectType: types.ObjectType{
						AttrTypes: CallHookValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"call_status_hook": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"method": schema.StringAttribute{
						Optional: true,
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"GET",
								"POST",
							),
						},
						Default: stringdefault.StaticString("POST"),
					},
					"password": schema.StringAttribute{
						Required:  true,
						Sensitive: true,
					},
					"url": schema.StringAttribute{
						Required: true,
					},
					"username": schema.StringAttribute{
						Required: true,
					},
					"webhook_sid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: CallStatusHookType{
					ObjectType: types.ObjectType{
						AttrTypes: CallStatusHookValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"messaging_hook": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"method": schema.StringAttribute{
						Optional: true,
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"GET",
								"POST",
							),
						},
						Default: stringdefault.StaticString("POST"),
					},
					"password": schema.StringAttribute{
						Required:  true,
						Sensitive: true,
					},
					"url": schema.StringAttribute{
						Required: true,
					},
					"username": schema.StringAttribute{
						Required: true,
					},
					"webhook_sid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: MessagingHookType{
					ObjectType: types.ObjectType{
						AttrTypes: MessagingHookValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "application name",
				MarkdownDescription: "application name",
			},
			"record_all_calls": schema.Int64Attribute{
				Required: true,
				Validators: []validator.Int64{
					int64validator.OneOf(
						0,
						1,
					),
				},
			},
		},
	}
}

type ApplicationModel struct {
	AccountSid     types.String        `tfsdk:"account_sid"`
	ApplicationSid types.String        `tfsdk:"application_sid"`
	CallHook       CallHookValue       `tfsdk:"call_hook"`
	CallStatusHook CallStatusHookValue `tfsdk:"call_status_hook"`
	MessagingHook  MessagingHookValue  `tfsdk:"messaging_hook"`
	Name           types.String        `tfsdk:"name"`
	RecordAllCalls types.Int64         `tfsdk:"record_all_calls"`
}

var _ basetypes.ObjectTypable = CallHookType{}

type CallHookType struct {
	basetypes.ObjectType
}

func (t CallHookType) Equal(o attr.Type) bool {
	other, ok := o.(CallHookType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CallHookType) String() string {
	return "CallHookType"
}

func (t CallHookType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return nil, diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return nil, diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return nil, diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CallHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewCallHookValueNull() CallHookValue {
	return CallHookValue{
		state: attr.ValueStateNull,
	}
}

func NewCallHookValueUnknown() CallHookValue {
	return CallHookValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCallHookValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CallHookValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CallHookValue Attribute Value",
				"While creating a CallHookValue value, a missing attribute value was detected. "+
					"A CallHookValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CallHookValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CallHookValue Attribute Type",
				"While creating a CallHookValue value, an invalid attribute value was detected. "+
					"A CallHookValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CallHookValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CallHookValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CallHookValue Attribute Value",
				"While creating a CallHookValue value, an extra attribute value was detected. "+
					"A CallHookValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CallHookValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCallHookValueUnknown(), diags
	}

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return NewCallHookValueUnknown(), diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return NewCallHookValueUnknown(), diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return NewCallHookValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewCallHookValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return NewCallHookValueUnknown(), diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return NewCallHookValueUnknown(), diags
	}

	return CallHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewCallHookValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CallHookValue {
	object, diags := NewCallHookValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCallHookValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CallHookType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCallHookValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCallHookValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCallHookValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCallHookValueMust(CallHookValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CallHookType) ValueType(ctx context.Context) attr.Value {
	return CallHookValue{}
}

var _ basetypes.ObjectValuable = CallHookValue{}

type CallHookValue struct {
	Method     basetypes.StringValue `tfsdk:"method"`
	Password   basetypes.StringValue `tfsdk:"password"`
	Url        basetypes.StringValue `tfsdk:"url"`
	Username   basetypes.StringValue `tfsdk:"username"`
	WebhookSid basetypes.StringValue `tfsdk:"webhook_sid"`
	state      attr.ValueState
}

func (v CallHookValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["method"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["webhook_sid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Method.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["method"] = val

		val, err = v.Password.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		val, err = v.WebhookSid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["webhook_sid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CallHookValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CallHookValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CallHookValue) String() string {
	return "CallHookValue"
}

func (v CallHookValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"method":      v.Method,
			"password":    v.Password,
			"url":         v.Url,
			"username":    v.Username,
			"webhook_sid": v.WebhookSid,
		})

	return objVal, diags
}

func (v CallHookValue) Equal(o attr.Value) bool {
	other, ok := o.(CallHookValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Method.Equal(other.Method) {
		return false
	}

	if !v.Password.Equal(other.Password) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	if !v.WebhookSid.Equal(other.WebhookSid) {
		return false
	}

	return true
}

func (v CallHookValue) Type(ctx context.Context) attr.Type {
	return CallHookType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CallHookValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CallStatusHookType{}

type CallStatusHookType struct {
	basetypes.ObjectType
}

func (t CallStatusHookType) Equal(o attr.Type) bool {
	other, ok := o.(CallStatusHookType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CallStatusHookType) String() string {
	return "CallStatusHookType"
}

func (t CallStatusHookType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return nil, diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return nil, diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return nil, diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CallStatusHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewCallStatusHookValueNull() CallStatusHookValue {
	return CallStatusHookValue{
		state: attr.ValueStateNull,
	}
}

func NewCallStatusHookValueUnknown() CallStatusHookValue {
	return CallStatusHookValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCallStatusHookValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CallStatusHookValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CallStatusHookValue Attribute Value",
				"While creating a CallStatusHookValue value, a missing attribute value was detected. "+
					"A CallStatusHookValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CallStatusHookValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CallStatusHookValue Attribute Type",
				"While creating a CallStatusHookValue value, an invalid attribute value was detected. "+
					"A CallStatusHookValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CallStatusHookValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CallStatusHookValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CallStatusHookValue Attribute Value",
				"While creating a CallStatusHookValue value, an extra attribute value was detected. "+
					"A CallStatusHookValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CallStatusHookValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCallStatusHookValueUnknown(), diags
	}

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return NewCallStatusHookValueUnknown(), diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return NewCallStatusHookValueUnknown(), diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return NewCallStatusHookValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewCallStatusHookValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return NewCallStatusHookValueUnknown(), diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return NewCallStatusHookValueUnknown(), diags
	}

	return CallStatusHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewCallStatusHookValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CallStatusHookValue {
	object, diags := NewCallStatusHookValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCallStatusHookValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CallStatusHookType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCallStatusHookValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCallStatusHookValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCallStatusHookValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCallStatusHookValueMust(CallStatusHookValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CallStatusHookType) ValueType(ctx context.Context) attr.Value {
	return CallStatusHookValue{}
}

var _ basetypes.ObjectValuable = CallStatusHookValue{}

type CallStatusHookValue struct {
	Method     basetypes.StringValue `tfsdk:"method"`
	Password   basetypes.StringValue `tfsdk:"password"`
	Url        basetypes.StringValue `tfsdk:"url"`
	Username   basetypes.StringValue `tfsdk:"username"`
	WebhookSid basetypes.StringValue `tfsdk:"webhook_sid"`
	state      attr.ValueState
}

func (v CallStatusHookValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["method"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["webhook_sid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Method.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["method"] = val

		val, err = v.Password.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		val, err = v.WebhookSid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["webhook_sid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CallStatusHookValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CallStatusHookValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CallStatusHookValue) String() string {
	return "CallStatusHookValue"
}

func (v CallStatusHookValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"method":      v.Method,
			"password":    v.Password,
			"url":         v.Url,
			"username":    v.Username,
			"webhook_sid": v.WebhookSid,
		})

	return objVal, diags
}

func (v CallStatusHookValue) Equal(o attr.Value) bool {
	other, ok := o.(CallStatusHookValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Method.Equal(other.Method) {
		return false
	}

	if !v.Password.Equal(other.Password) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	if !v.WebhookSid.Equal(other.WebhookSid) {
		return false
	}

	return true
}

func (v CallStatusHookValue) Type(ctx context.Context) attr.Type {
	return CallStatusHookType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CallStatusHookValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = MessagingHookType{}

type MessagingHookType struct {
	basetypes.ObjectType
}

func (t MessagingHookType) Equal(o attr.Type) bool {
	other, ok := o.(MessagingHookType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MessagingHookType) String() string {
	return "MessagingHookType"
}

func (t MessagingHookType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return nil, diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return nil, diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return nil, diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MessagingHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewMessagingHookValueNull() MessagingHookValue {
	return MessagingHookValue{
		state: attr.ValueStateNull,
	}
}

func NewMessagingHookValueUnknown() MessagingHookValue {
	return MessagingHookValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMessagingHookValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MessagingHookValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MessagingHookValue Attribute Value",
				"While creating a MessagingHookValue value, a missing attribute value was detected. "+
					"A MessagingHookValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MessagingHookValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MessagingHookValue Attribute Type",
				"While creating a MessagingHookValue value, an invalid attribute value was detected. "+
					"A MessagingHookValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MessagingHookValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MessagingHookValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MessagingHookValue Attribute Value",
				"While creating a MessagingHookValue value, an extra attribute value was detected. "+
					"A MessagingHookValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MessagingHookValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMessagingHookValueUnknown(), diags
	}

	methodAttribute, ok := attributes["method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`method is missing from object`)

		return NewMessagingHookValueUnknown(), diags
	}

	methodVal, ok := methodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`method expected to be basetypes.StringValue, was: %T`, methodAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return NewMessagingHookValueUnknown(), diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return NewMessagingHookValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewMessagingHookValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	webhookSidAttribute, ok := attributes["webhook_sid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_sid is missing from object`)

		return NewMessagingHookValueUnknown(), diags
	}

	webhookSidVal, ok := webhookSidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_sid expected to be basetypes.StringValue, was: %T`, webhookSidAttribute))
	}

	if diags.HasError() {
		return NewMessagingHookValueUnknown(), diags
	}

	return MessagingHookValue{
		Method:     methodVal,
		Password:   passwordVal,
		Url:        urlVal,
		Username:   usernameVal,
		WebhookSid: webhookSidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewMessagingHookValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MessagingHookValue {
	object, diags := NewMessagingHookValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMessagingHookValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MessagingHookType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMessagingHookValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMessagingHookValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMessagingHookValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMessagingHookValueMust(MessagingHookValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MessagingHookType) ValueType(ctx context.Context) attr.Value {
	return MessagingHookValue{}
}

var _ basetypes.ObjectValuable = MessagingHookValue{}

type MessagingHookValue struct {
	Method     basetypes.StringValue `tfsdk:"method"`
	Password   basetypes.StringValue `tfsdk:"password"`
	Url        basetypes.StringValue `tfsdk:"url"`
	Username   basetypes.StringValue `tfsdk:"username"`
	WebhookSid basetypes.StringValue `tfsdk:"webhook_sid"`
	state      attr.ValueState
}

func (v MessagingHookValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["method"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["webhook_sid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Method.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["method"] = val

		val, err = v.Password.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		val, err = v.WebhookSid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["webhook_sid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MessagingHookValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MessagingHookValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MessagingHookValue) String() string {
	return "MessagingHookValue"
}

func (v MessagingHookValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"method":      v.Method,
			"password":    v.Password,
			"url":         v.Url,
			"username":    v.Username,
			"webhook_sid": v.WebhookSid,
		})

	return objVal, diags
}

func (v MessagingHookValue) Equal(o attr.Value) bool {
	other, ok := o.(MessagingHookValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Method.Equal(other.Method) {
		return false
	}

	if !v.Password.Equal(other.Password) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	if !v.WebhookSid.Equal(other.WebhookSid) {
		return false
	}

	return true
}

func (v MessagingHookValue) Type(ctx context.Context) attr.Type {
	return MessagingHookType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MessagingHookValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"method":      basetypes.StringType{},
		"password":    basetypes.StringType{},
		"url":         basetypes.StringType{},
		"username":    basetypes.StringType{},
		"webhook_sid": basetypes.StringType{},
	}
}
